name: Rasmus Lasthein
favicon: null
layout_spectrum: 0.742414279608056
typography_spectrum: 0.7057198456022888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.31770947319455445
  lightness: 0.3837080029770732
  saturation: 0.15350626967847347
  rhythmicContrast: 0.7721940816845745
purpose: []
